### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by samny** [skidding/react-cosmos#208]
I'm using comsos-js 0.7.3 from npm in my project using React 15.x. Everything seems to be working perfectly, but I get some dependency errors I would like to get rid of. I guess it should be a simple package.json update?

```
npm ERR! peer invalid: react-dom@^0.14.8, required by react-component-playground@0.4.1
npm ERR! peer invalid: react@^0.14.8, required by react-component-playground@0.4.1
```

**Comment by skidding** [comment]
Hi @samny,

Can you please switch from `cosmos-js@0.7.3` to `react-cosmos@1.0.0-beta.1` (strict version, no ^ caret)? It should just work. Thanks.

**Comment by samny** [comment]
Sweet! Thanks for the quick reply @skidding, works like a charm :)
